OP-315 follow-up (also related to OP-338)
informatici/openhospital pull request #149
Opened 2020-12-10 22:30 UTC by mizzioisf

Updated oh.bat
Aligned all configuration and related files

2020-12-12 00:24 UTC, mwithi approved these changes
Works for me!

But I had to:
- add `/var/log` and /`var/log/mysqld` folders
- change to `set MYSQL_DIR=mysql-5.7.30-win32`
- change to `set JAVA_DIR="jdk-11.0.9+11-jre"`

don't know why these little changes in Windows.


For missing folders just create and commit them with a .gitignore inside like this
```
# Ignore everything in this directory
*
# Except this file
!.gitignore
```

2020-12-14 00:19 UTC, mizzioisf commented
Thank you for the test !

- aligned mysql version to 5.7.31 everywhere, also in Makefile
- jdk file is: jdk-11.0.9.1+1, could you please double check ?

Regarding the paths you are definitely right, I will push later a reviewed version. 
We don't need to have or pack empty directories anymore: the scripts take care of crating everything, which is also parametric and user adjustable.
The default is now clean and simple and **common to all distros**:

/tmp
/data
data/db
data/log
data/dicom_storage

2021-01-08 16:20 UTC, mwithi requested changes
Also `docker-compose` is no longer needed
[Line 107](https://github.com/informatici/openhospital/pull/149/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R107)
[Line 109](https://github.com/informatici/openhospital/pull/149/files#diff-76ed074a9305c04054cdebb9e9aad2d818052b07091de1f20cad0bbac34ffb52R109)

2021-01-08 16:20 UTC, mwithi commented on poh-bundle-win/oh/rsc/log4j.properties.dist
> +log4j.rootCategory=info,RollingFile
Why lowercase here?

2021-01-08 17:07 UTC, mwithi approved these changes

2021-01-08 17:08 UTC, merged